### ISSUE TITLE
Office 365 Installation

### ISSUE THREAD

**Issue by KD33** [Excel-DNA/WiXInstaller#15]
Hello,

Thanks for the installer.  I've had some success installing on Office 16, but do you have any insight on how one can get this to install on Office365?  Specifically, I'm having issues with the registry.  Here's the output from my installation logs:

Enter try block of CaRegisterAddIn
Retrieving Registry Information for : Software\Microsoft\Office\11.0
Unable to retrieve registry Information for : Software\Microsoft\Office\11.0
Retrieving Registry Information for : Software\Microsoft\Office\12.0
Unable to retrieve registry Information for : Software\Microsoft\Office\12.0
Retrieving Registry Information for : Software\Microsoft\Office\14.0
Unable to retrieve registry Information for : Software\Microsoft\Office\14.0
Retrieving Registry Information for : Software\Microsoft\Office\15.0
Unable to retrieve registry Information for : Software\Microsoft\Office\15.0
Retrieving Registry Information for : Software\Microsoft\Office\16.0
Unable to retrieve registry Information for : Software\Microsoft\Office\16.0
End CaRegisterAddIn

Thanks

**Comment by andrewkittredge** [comment]
We have had problems too.  I am installing 365 to see if I can figure it out.

**Comment by KD33** [comment]
So it's not an issue with 365, as I was able to get this to work on another machine that uses 365

What I think is happening is that this template assumes there is a registry already there in the form of Software\Microsoft\Office\16.0\Excel\Options.  On machines where I was able to get this Installer to work, this registry was already there.  I think the CustomAction would therefore need to check if this registry exists, and if not create it.

**Comment by KD33** [comment]
Fixed.  The solution was to create the registry if it wasn't already there.

**Comment by andrewkittredge** [comment]
@KD33 Can you share the change you made to get this working?

**Comment by andrewkittredge** [comment]
FWIW, I just setup up a fresh VM, installed Excel 365, and installed our Excel-DNA Add-in with no problems.  Perhaps Microsoft modified the Excel installation.
